language: ruby
bundler_args: --without development production
rvm:
  - 1.9.3
env:
  - DB=mysql
before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -e 'create database travis_whattheme__api;'
  - rake db:migrate
  - rake db:test:prepare
script:
  - bundle exec cucumber features/ --quiet
